import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Footer from "@/components/footer";
import Wrapper from "@/components/wrapper";
import { Toaster } from "@/components/ui/toaster";
import PreviewModal from "@/components/preview-modal";
import UpdateSizeModal from "@/components/update-size-model";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Toaster />
        <PreviewModal />
        <UpdateSizeModal />
        <Wrapper>{children}</Wrapper>
        <Footer />
      </body>
    </html>
  );
}
